export const SONG_PLAYLIST = [
{
id: 1,
title: "A Boy Who Only Dreams",
artist: "Eddie Lee",
src: import.meta.env.VITE_SONG_1_URL,
},
{
id: 2,
title: "Search One's Memory",
artist: "Eddie Lee",
src: import.meta.env.VITE_SONG_2_URL,
},
{
id: 3,
title: "To My Precious Person",
artist: "Eddie Lee",
src: import.meta.env.VITE_SONG_3_URL,
},
{
id: 4,
title: "Good Night & See You",
artist: "Akiko Shina",
src: import.meta.env.VITE_SONG_4_URL,
},
{
id: 5,
title: "In Your Arm",
artist: "Akiko Shina",
src: import.meta.env.VITE_SONG_5_URL,
},
{
id: 6,
title: "Sweet Moment",
artist: "Akiko Shina",
src: import.meta.env.VITE_SONG_6_URL,
},
{
id: 7,
title: "Velvet Night",
artist: "Akiko Shina",
src: import.meta.env.VITE_SONG_7_URL,
},
{
id: 8,
title: "Hypnosis",
artist: "Eco Art",
src: import.meta.env.VITE_SONG_8_URL,
},
{
id: 9,
title: "Lightyears",
artist: "Eco Art",
src: import.meta.env.VITE_SONG_9_URL,
},
{
id: 10,
title: "Silent Horizons",
artist: "Eco Art",
src: import.meta.env.VITE_SONG_10_URL,
},
{
id: 11,
title: "Time To Ponder",
artist: "Hirohasaimoto",
src: import.meta.env.VITE_SONG_11_URL,
},
{
id: 12,
title: "Cinematic Lofi",
artist: "Lofi NG",
src: import.meta.env.VITE_SONG_12_URL,
},
{
id: 13,
title: "Nemuko",
artist: "Lofi",
src: import.meta.env.VITE_SONG_13_URL,
},
{
id: 14,
title: "Free Beat",
artist: "Oyatsubeats",
src: import.meta.env.VITE_SONG_14_URL,
},
{
id: 15,
title: "Chill Lofi Song",
artist: "Virtuosound",
src: import.meta.env.VITE_SONG_15_URL,
},
{
id: 16,
title: "Moody Lofi Song",
artist: "Virtuosound",
src: import.meta.env.VITE_SONG_16_URL,
},
{
id: 17,
title: "Dream Glitch Ambient",
artist: "Welc0mei0",
src: import.meta.env.VITE_SONG_17_URL,
},
{
id: 18,
title: "Ambient IDM Water",
artist: "Welc0mei0",
src: import.meta.env.VITE_SONG_18_URL,
},
{
id: 19,
title: "Piano Ambient Relaxing",
artist: "Welc0mei0",
src: import.meta.env.VITE_SONG_19_URL,
},
{
id: 20,
title: "Simple Day Nostalgic",
artist: "Welc0mei0",
src: import.meta.env.VITE_SONG_20_URL,
},
];
